### PR TITLE
image gallery concept

### PR DESCRIPTION
**Pull request by skippy**

### CODE REVIEW

**Comment by skippy** [comment]
@icegulch I put up a PR just so we can comment on stuff.  Thoughts:
- I would like to be able to use this in multiple places, though I think 1 per page is an acceptable constraint
- for other places (who we are, 24/7 Emergency Services, Contact Us), those are all  (or can be) 2 column layouts, so the same styling should work across all of them?)
- the array can be populated from a file that is modified by the admin screen, so we can have the admin upload images into a folder, then save that reference in a config file which this draws upon.  
- What if we want more or less than 5 images?  Is that going to be a design constraint?  I think i'm ok if it is... I can require 5 images in the admin screen, but curious on your thoughts. 

I think we can move forward in two ways:
- you continue to run with it!
- or I can pickup the admin and coding if you want to work on finishing styling and what not.  

totally your call!  

On a related note, when I first saw this, i thought why are we recreating the wheel?!  But this is simple, elegant, and at least the other carousels I found were pretty darn convoluted as they tried to do EVERYTHING..>!

**Comment by icegulch** [comment]
@skippy we could also look into simply having some kind of grid for images where thumbnails are clickable popping a lightbox with a larger version of the image. That would make the responsive-side of things easier and keep things flexible from the admin side of things. See attached for quick ideas. Happy to discuss on call too.

masonry-layout-1-1
css-grid-gallery-after

**Comment by skippy** [comment]
@kvenegassjifire do you have a preference?  See the preview link for a working prototype of a simple implementation.  We can make it more complex from here, and this preview has an odd constraint (basically a pre-set number of images).   Anyway, what do you think?

**Comment by kvenegassjifire** [comment]
I love it! Actually, limiting it to 5 images would be perfect because we rarely have a surplus of high-res, community-appropriate images to share. Thumbs up from me as is.
________________________________

**Comment by skippy** [comment]
Awesome!!  @icegulch If you're ok with it, I can pick this up and get it hooked into the admin screen

@kvenegassjifire i was thinking of adding this widget to the home and about us pages.  I can preload the images but if you have imgs that you want, can you attach them here?

**Comment by skippy** [comment]
@kvenegassjifire and @icegulch what ya think on this latest version?

**Pull request merged**
