### PR TITLE
customizable home header photos

### PR DESCRIPTION
**Pull request by icegulch**

### CODE REVIEW

**Comment by skippy** [comment]
@icegulch looking at the preview, no image shows up... I suspect that is because it is looking to the main site for the image.  Can we use a relative instead of absolute URL?

**Comment by icegulch** [comment]
Hi, @skippy. I think the issue was that the photos needed to be on "sjifire.org" in order for Cloudinary to agree to "fetch" them. I'm not able to test the CMS-side of things but I did try to update the `config.yml` so that those homepage banner photos would be customizable. Mind testing? Oh, and I also de-red-ified things, as we discussed on the phone (tone down the "fire" side of things).

**Comment by skippy** [comment]
nope, it's working!  see the preview app https://deploy-preview-322--sjifire.netlify.app/

**Comment by skippy** [comment]
can we get the image to pop a bit more (ie, less opacity/gray overlap?)

**Comment by skippy** [comment]
@icegulch I'm going to merge this in as it is a big ask of what @kvenegassjifire wants.  However, lets make that image pop a bit more?

**Pull request merged**
